<!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><title>Solicitud #{{ $application->id }} | Panel de MINKA</title>@vite(['resources/css/app.css'])
@include('partials.favicon')
</head>
<body class="panel-body"><header class="panel-header"><strong>ORBYNIA · Panel de MINKA</strong><a href="{{ route('minka.commercial') }}">Volver a gestión comercial</a></header><main class="panel-main panel-detail"><h1>{{ $application->company_name }}</h1><p><strong>Responsable:</strong> {{ $application->first_name }} {{ $application->last_name }} · {{ $application->email }} · {{ $application->phone }}</p><p><strong>Subdominio solicitado:</strong> {{ $application->requested_slug }}.orbynia.com · <strong>Plan de interés:</strong> {{ ucfirst($application->plan_interest) }}</p><p><strong>Estado:</strong> {{ $application->status }} · <strong>Correo verificado:</strong> {{ $application->email_verified_at ? 'Sí' : 'Pendiente' }} · <strong>Reserva:</strong> {{ $application->reserved_slug ? $application->reserved_slug.'.orbynia.com' : 'Sin reservar' }}</p>
<p><a href="{{ route('minka.sales.show', ['solicitud', $application->id]) }}">Abrir seguimiento comercial y propuestas</a></p>
@if(session('panel_success'))<div class="form-success" role="status">{{ session('panel_success') }}</div>@endif
@if($errors->any())<div class="form-alert" role="alert">{{ $errors->first() }}</div>@endif
@if($application->status === 'pending_review')
<section class="panel-card"><h2>Aprobar evaluación</h2><p>El subdominio ya está reservado tras la verificación del correo. La aprobación confirma su asignación; después se prepara la instancia de forma asistida.</p><form method="post" action="{{ route('minka.application.approve', $application->id) }}">@csrf<label for="evaluation_ends_at">Fin acordado de evaluación</label><input id="evaluation_ends_at" name="evaluation_ends_at" type="date" required><fieldset><legend>Módulos que tendrá esta empresa</legend>@foreach($modules as $key => $label)<label class="panel-check"><input type="checkbox" name="enabled_modules[]" value="{{ $key }}" @checked(in_array($key, $selectedModules, true))>{{ $label }}</label>@endforeach</fieldset><label for="operator_notes">Notas internas</label><textarea id="operator_notes" name="operator_notes" rows="4">{{ old('operator_notes', $application->operator_notes) }}</textarea><button class="button button-primary" type="submit">Aprobar solicitud</button></form></section>
<section class="panel-card"><h2>Rechazar solicitud</h2><form method="post" action="{{ route('minka.application.reject', $application->id) }}">@csrf<label for="reason">Motivo interno</label><textarea id="reason" name="reason" required maxlength="1000"></textarea><button type="submit">Rechazar</button></form></section>
@endif
@if($application->status === 'slug_conflict')
<section class="panel-card"><h2>Subdominio no disponible</h2><p>El correo está confirmado, pero otra empresa reservó el nombre solicitado. El enlace de confirmación permite al solicitante elegir otro nombre. Si ya no continuará, puedes rechazar esta solicitud.</p><form method="post" action="{{ route('minka.application.reject', $application->id) }}">@csrf<label for="conflict-reason">Motivo interno</label><textarea id="conflict-reason" name="reason" required maxlength="1000"></textarea><button type="submit">Rechazar solicitud</button></form></section>
@endif
@if($application->status === 'approved')
<section class="panel-card"><h2>Activación asistida</h2><ol><li>Preparar el ERP y sus bases aisladas en {{ $application->approved_slug }}.orbynia.com.</li><li>Aplicar los módulos: {{ implode(', ', $selectedModules) }} y la fecha {{ $application->evaluation_ends_at }}.</li><li>Ejecutar <code>php artisan minka:create-admin</code> en esa instancia con el correo del primer ADMIN que registrarás abajo.</li><li>Comprobar que el enlace de invitación llegó y el ERP responde.</li></ol><form method="post" action="{{ route('minka.application.activate', $application->id) }}">@csrf<label for="admin_email">Correo del primer ADMIN del ERP</label><input id="admin_email" name="admin_email" type="email" value="{{ old('admin_email', $application->admin_email ?: $application->email) }}" required maxlength="190"><p class="field-hint">Se usará solo para localizar el acceso de esta empresa desde la landing. Debe coincidir con el correo usado en <code>minka:create-admin</code>.</p><label class="panel-check"><input type="checkbox" name="instance_ready" value="1" required>Confirmo que la instancia, módulos e invitación están listos.</label><button class="button button-primary" type="submit">Marcar activa</button></form></section>
@endif
<section class="panel-card"><h2>Historial</h2><ul>@foreach($events as $event)<li>{{ $event->created_at }} · {{ $event->event }} @if($event->details) — {{ $event->details }}@endif</li>@endforeach</ul></section></main></body></html>
